### PR TITLE
Update pokedex.json for Gen 8

### PR DESCRIPTION
**Pull request by Blossomstripe**
Update new pokemons in Gen 8

### CODE REVIEW

**Comment by Blossomstripe** [comment]
New version also solved Issue #33

**Comment by HybridShivam** [comment]
Why this hasn't been merged yet ?

**Review by MagnusBuch — CHANGES_REQUESTED** [review]
```
{
    "id": 827,
    "name": {
      "english": "Nickit",
      "japanese": "クスネ",
      "chinese": "偷儿狐",
      "french": "Goupilou"
    },
    "type": [
      "Dark"
    ],
    "base": {
      "HP": 40,
      "Attack": 28,
      "Defense": 28,
      "Sp. Attack": 47,
      "Sp. Defense": 52,
      **"Speed": 40**
    }
  },
```
should be:
```
{
    "id": 827,
    "name": {
      "english": "Nickit",
      "japanese": "クスネ",
      "chinese": "偷儿狐",
      "french": "Goupilou"
    },
    "type": [
      "Dark"
    ],
    "base": {
      "HP": 40,
      "Attack": 28,
      "Defense": 28,
      "Sp. Attack": 47,
      "Sp. Defense": 52,
      **"Speed": 50**
    }
  },
```
Nickits speed should be 50, but that's the only fault I found, everything else looks good!

**Comment by Blossomstripe** [comment]
@MagnusBuch Thanks for your notice! I found that this is an error of zh-cn pokemon wiki, and now I've fixed it.

**Review by MagnusBuch — APPROVED** [review]

**Pull request closed without merging**
